export interface Article {
  slug: string
  title: string
  description: string
  category: string
  categoryColor: string
  categoryText: string
  readTime: number
  publishedAt: string
  relatedTool?: string
  relatedToolName?: string
  lang: 'en' | 'th'
  keywords: string[]
}

export const articles: Article[] = [
  // Dev / IT
  {
    slug: 'what-is-jwt',
    title: 'What is JWT? Understanding JSON Web Tokens',
    description: 'A complete guide to JSON Web Tokens — how they work, what the header, payload, and signature mean, and when to use them in your applications.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-04-01',
    relatedTool: 'jwt-decoder',
    relatedToolName: 'JWT Decoder',
    lang: 'en',
    keywords: ['jwt', 'json web token', 'jwt tutorial', 'jwt explained', 'jwt header payload signature'],
  },
  {
    slug: 'base64-encoding-explained',
    title: 'Base64 Encoding Explained: What It Is and When to Use It',
    description: 'Learn what Base64 encoding is, how it works, why it exists, and common use cases including JWT, data URIs, and API payloads.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-04-02',
    relatedTool: 'base64-encode-decode',
    relatedToolName: 'Base64 Encode / Decode',
    lang: 'en',
    keywords: ['base64 encoding', 'base64 explained', 'what is base64', 'base64 use cases'],
  },
  {
    slug: 'cidr-subnetting-guide',
    title: 'CIDR Notation and Subnetting: A Complete Guide',
    description: 'Master CIDR notation and subnetting. Learn how to calculate network addresses, host ranges, broadcast addresses, and usable IPs from any CIDR block.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-04-03',
    relatedTool: 'cidr-calculator',
    relatedToolName: 'CIDR Calculator',
    lang: 'en',
    keywords: ['cidr notation', 'subnetting guide', 'cidr explained', 'subnet calculator', 'ip addressing'],
  },
  {
    slug: 'regex-guide-for-developers',
    title: 'Regular Expressions (Regex) Guide for Developers',
    description: 'A practical regex guide with real examples. Learn anchors, character classes, quantifiers, groups, and lookaheads — with patterns you can use today.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 9,
    publishedAt: '2025-04-04',
    relatedTool: 'regex-tester',
    relatedToolName: 'Regex Tester',
    lang: 'en',
    keywords: ['regex tutorial', 'regular expressions guide', 'regex examples', 'learn regex'],
  },
  {
    slug: 'hash-functions-md5-sha256-sha512',
    title: 'MD5 vs SHA-1 vs SHA-256 vs SHA-512: Hash Functions Explained',
    description: 'Understand cryptographic hash functions, the differences between MD5, SHA-1, SHA-256, and SHA-512, and which one to use for your security needs.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-04-05',
    relatedTool: 'hash-generator',
    relatedToolName: 'Hash Generator',
    lang: 'en',
    keywords: ['md5 vs sha256', 'hash functions explained', 'cryptographic hash', 'sha256 sha512 difference'],
  },
  {
    slug: 'cron-expression-guide',
    title: 'Cron Expression Guide: Schedule Jobs Like a Pro',
    description: 'Master cron syntax with this complete guide. Learn every field, special characters, common patterns, and how to schedule jobs on Linux, AWS, and Kubernetes.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-04-06',
    relatedTool: 'cron-builder',
    relatedToolName: 'Cron Builder',
    lang: 'en',
    keywords: ['cron expression', 'cron syntax', 'cron job guide', 'cron schedule'],
  },
  {
    slug: 'uuid-guide',
    title: 'UUID Explained: v1, v4, v5 and When to Use Each',
    description: 'Everything you need to know about UUIDs — the difference between v1, v4, and v5, how they are generated, and best practices for using them in databases and APIs.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-04-07',
    relatedTool: 'uuid-generator',
    relatedToolName: 'UUID Generator',
    lang: 'en',
    keywords: ['uuid explained', 'uuid v4 vs v1', 'what is uuid', 'uuid best practices'],
  },
  {
    slug: 'unix-timestamp-explained',
    title: 'Unix Timestamps Explained: Epoch Time, Seconds vs Milliseconds',
    description: 'Learn what Unix timestamps are, how epoch time works, the difference between seconds and milliseconds timestamps, and how to convert them in any programming language.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-04-08',
    relatedTool: 'unix-timestamp',
    relatedToolName: 'Unix Timestamp Converter',
    lang: 'en',
    keywords: ['unix timestamp', 'epoch time explained', 'unix time seconds milliseconds'],
  },
  {
    slug: 'json-yaml-comparison',
    title: 'JSON vs YAML: Differences, Use Cases, and When to Use Each',
    description: 'A detailed comparison of JSON and YAML formats — syntax differences, readability, use cases in DevOps and APIs, and how to convert between them.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-04-09',
    relatedTool: 'json-to-yaml',
    relatedToolName: 'JSON ↔ YAML Converter',
    lang: 'en',
    keywords: ['json vs yaml', 'yaml vs json', 'json yaml difference', 'when to use yaml'],
  },
  // OpenSSL & Cert
  {
    slug: 'ssl-certificate-types-explained',
    title: 'SSL Certificate Types Explained: PEM, DER, PKCS12, and More',
    description: 'A complete guide to SSL certificate formats — PEM, DER, PKCS12/PFX, and PKCS8. Learn what each format is, when to use it, and how to convert between them.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-04-10',
    relatedTool: 'pem-der-converter',
    relatedToolName: 'PEM ↔ DER Converter',
    lang: 'en',
    keywords: ['ssl certificate formats', 'pem vs der', 'pkcs12 explained', 'ssl cert types'],
  },
  {
    slug: 'self-signed-certificate-guide',
    title: 'How to Create a Self-signed SSL Certificate for Local Development',
    description: 'Step-by-step guide to generating self-signed SSL certificates for localhost, development environments, and internal services using OpenSSL and browser tools.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 8,
    publishedAt: '2025-04-11',
    relatedTool: 'self-signed-cert',
    relatedToolName: 'Self-signed Cert Generator',
    lang: 'en',
    keywords: ['self signed certificate', 'localhost ssl', 'development ssl certificate', 'openssl self signed'],
  },
  {
    slug: 'what-is-csr',
    title: 'What is a CSR? How to Generate and Submit a Certificate Signing Request',
    description: 'Learn what a Certificate Signing Request (CSR) is, what information it contains, how to generate one, and how to submit it to a Certificate Authority to get an SSL certificate.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-04-12',
    relatedTool: 'csr-generator',
    relatedToolName: 'CSR Generator',
    lang: 'en',
    keywords: ['what is csr', 'certificate signing request', 'how to generate csr', 'ssl csr guide'],
  },
  {
    slug: 'tls-versions-explained',
    title: 'TLS 1.0, 1.1, 1.2, and 1.3: Differences and Why Versions Matter',
    description: 'Understand the differences between TLS 1.0, 1.1, 1.2, and 1.3. Learn why older versions are deprecated, what security improvements TLS 1.3 brings, and how to check what your server supports.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-04-13',
    relatedTool: 'openssl-command-builder',
    relatedToolName: 'OpenSSL Command Builder',
    lang: 'en',
    keywords: ['tls versions', 'tls 1.2 vs 1.3', 'ssl tls differences', 'tls explained'],
  },
  {
    slug: 'rsa-encryption-explained',
    title: 'RSA Encryption Explained: Public Keys, Private Keys, and How It Works',
    description: 'A clear explanation of RSA asymmetric encryption — how public and private keys work, key sizes (1024 vs 2048 vs 4096-bit), digital signatures, and practical use cases.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 8,
    publishedAt: '2025-04-14',
    relatedTool: 'rsa-key-generator',
    relatedToolName: 'RSA Key Generator',
    lang: 'en',
    keywords: ['rsa encryption', 'public private key', 'asymmetric encryption', 'rsa explained'],
  },
  // Thai Tools (Thai language)
  {
    slug: 'thai-income-tax-2568-guide',
    title: 'วิธีคำนวณภาษีเงินได้บุคคลธรรมดา 2568 พร้อมค่าลดหย่อนครบทุกรายการ',
    description: 'คู่มือคำนวณภาษีเงินได้บุคคลธรรมดาปี 2568 ครบถ้วน ตั้งแต่ประเภทเงินได้ ค่าใช้จ่าย ค่าลดหย่อนทุกรายการ อัตราภาษีขั้นบันได พร้อมตัวอย่างการคำนวณ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 10,
    publishedAt: '2025-04-15',
    relatedTool: 'thai-tax-calculator',
    relatedToolName: 'คำนวณภาษีเงินได้บุคคลธรรมดา 2568',
    lang: 'th',
    keywords: ['ภาษีเงินได้บุคคลธรรมดา 2568', 'คำนวณภาษี 2568', 'ลดหย่อนภาษี 2568', 'อัตราภาษีบุคคลธรรมดา'],
  },
  {
    slug: 'thai-baht-to-words-guide',
    title: 'วิธีเขียนจำนวนเงินเป็นตัวอักษรภาษาไทยบนเช็คให้ถูกต้อง',
    description: 'คู่มือการเขียนจำนวนเงินเป็นตัวอักษรภาษาไทยสำหรับเขียนเช็ค ใบสำคัญจ่าย และเอกสารทางกฎหมาย พร้อมตัวอย่างและข้อควรระวัง',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 5,
    publishedAt: '2025-04-16',
    relatedTool: 'thai-baht-to-words',
    relatedToolName: 'จำนวนเงินบาทเป็นตัวอักษร',
    lang: 'th',
    keywords: ['เขียนเช็คภาษาไทย', 'จำนวนเงินเป็นตัวอักษร', 'เขียนตัวเลขเป็นคำ', 'บาทเป็นตัวอักษร'],
  },
  {
    slug: 'thai-date-converter-guide',
    title: 'พ.ศ. กับ ค.ศ. ต่างกันอย่างไร? วิธีแปลงวันที่ไทยและสากล',
    description: 'อธิบายความแตกต่างระหว่างปีพุทธศักราช (พ.ศ.) และคริสต์ศักราช (ค.ศ.) สูตรการแปลง และวิธีใช้งานในเอกสารราชการและธุรกิจระหว่างประเทศ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 4,
    publishedAt: '2025-04-17',
    relatedTool: 'thai-date-converter',
    relatedToolName: 'Thai Date Converter',
    lang: 'th',
    keywords: ['พ.ศ. ค.ศ. ต่างกันอย่างไร', 'แปลงวันที่ไทย', 'พุทธศักราช คริสต์ศักราช', 'แปลงปี พ.ศ.'],
  },
  // File & Image
  {
    slug: 'image-compression-guide',
    title: 'Image Compression Guide: Reduce File Size Without Losing Quality',
    description: 'Learn how image compression works, the difference between lossy and lossless compression, optimal quality settings, and when to use JPG, PNG, or WebP for your website.',
    category: 'File & Image',
    categoryColor: '#faeeda',
    categoryText: '#633806',
    readTime: 6,
    publishedAt: '2025-04-18',
    relatedTool: 'image-compressor',
    relatedToolName: 'Image Compressor',
    lang: 'en',
    keywords: ['image compression', 'compress images', 'jpg vs png vs webp', 'image optimization'],
  },
  {
    slug: 'qr-code-guide',
    title: 'QR Codes Explained: How They Work and Best Practices',
    description: 'Everything about QR codes — how they store data, error correction levels, size recommendations, and best practices for generating QR codes that scan reliably.',
    category: 'File & Image',
    categoryColor: '#faeeda',
    categoryText: '#633806',
    readTime: 5,
    publishedAt: '2025-04-19',
    relatedTool: 'qr-code-generator',
    relatedToolName: 'QR Code Generator',
    lang: 'en',
    keywords: ['qr code explained', 'how qr codes work', 'qr code best practices', 'qr code guide'],
  },

  // ── New articles (Batch 2) ────────────────────────────────────

  // Dev / IT
  {
    slug: 'json-formatting-guide',
    title: "JSON Formatting and Validation: A Developer's Complete Guide",
    description: 'Learn how to format, validate, and minify JSON correctly. Covers JSON syntax rules, common errors, indentation best practices, and when to minify vs pretty-print for APIs and config files.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-01',
    relatedTool: 'json-formatter',
    relatedToolName: 'JSON Formatter',
    lang: 'en',
    keywords: ['json format', 'json validation', 'json syntax', 'pretty print json', 'json minify', 'json best practices'],
  },
  {
    slug: 'url-encoding-explained',
    title: 'URL Encoding Explained: Percent-Encoding, encodeURI vs encodeURIComponent',
    description: 'Understand URL encoding (percent-encoding) — why it exists, how %20 and other sequences work, and the critical difference between encodeURI and encodeURIComponent in JavaScript.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-05-02',
    relatedTool: 'url-encode-decode',
    relatedToolName: 'URL Encode / Decode',
    lang: 'en',
    keywords: ['url encoding', 'percent encoding', 'encodeuri vs encodeuricomponent', 'url encode decode', 'url special characters'],
  },
  {
    slug: 'password-security-guide',
    title: 'Password Security Guide: What Makes a Strong Password and How to Generate One',
    description: 'Everything you need to know about password strength — entropy, character sets, length requirements, why password managers matter, and how cryptographically secure random generators work.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-03',
    relatedTool: 'password-generator',
    relatedToolName: 'Password Generator',
    lang: 'en',
    keywords: ['password security', 'strong password', 'password entropy', 'password generator', 'secure password tips'],
  },
  {
    slug: 'json-to-csv-guide',
    title: 'JSON to CSV Conversion: How to Export JSON Data for Excel and Google Sheets',
    description: 'Learn how to convert JSON arrays to CSV format for spreadsheets. Covers flattening nested objects, handling special characters, choosing delimiters, and converting CSV back to JSON for APIs.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-05-04',
    relatedTool: 'json-to-csv',
    relatedToolName: 'JSON ↔ CSV Converter',
    lang: 'en',
    keywords: ['json to csv', 'convert json to csv', 'json excel', 'csv format', 'json array csv'],
  },
  {
    slug: 'css-color-formats-explained',
    title: 'CSS Color Formats Explained: HEX, RGB, HSL, and When to Use Each',
    description: 'A complete guide to CSS color formats — how HEX, RGB, RGBA, HSL, and HSLA work, how to convert between them, and which format to use for web design, theming, and accessibility.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-05',
    relatedTool: 'color-converter',
    relatedToolName: 'Color Converter',
    lang: 'en',
    keywords: ['css color formats', 'hex vs rgb', 'hsl color', 'rgba explained', 'color converter css', 'web colors guide'],
  },
  {
    slug: 'markdown-guide',
    title: 'Markdown Guide: Complete Syntax Reference for Developers and Writers',
    description: 'Master Markdown syntax from basics to advanced features. Covers headings, bold, italic, tables, code blocks, links, images, GitHub Flavored Markdown (GFM), and tips for README files and documentation.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-05-06',
    relatedTool: 'markdown-preview',
    relatedToolName: 'Markdown Preview',
    lang: 'en',
    keywords: ['markdown guide', 'markdown syntax', 'markdown tutorial', 'github markdown', 'readme markdown', 'markdown cheatsheet'],
  },
  {
    slug: 'content-length-seo-guide',
    title: 'Content Length and SEO: How Many Words Do You Really Need?',
    description: 'Does word count affect SEO rankings? Learn what Google actually says about content length, optimal blog post length by type, character limits for meta tags and social media, and how to measure readability.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-07',
    relatedTool: 'word-counter',
    relatedToolName: 'Word Counter',
    lang: 'en',
    keywords: ['content length seo', 'word count seo', 'ideal blog post length', 'character count', 'seo content guide'],
  },

  // File & Image
  {
    slug: 'favicon-guide',
    title: 'Favicon Guide: Sizes, Formats, and How to Add One to Your Website',
    description: 'Everything about favicons — all the sizes you need (16px to 512px), ICO vs PNG vs SVG formats, Apple touch icons, PWA icons, and exactly how to add favicon HTML tags to your site.',
    category: 'File & Image',
    categoryColor: '#faeeda',
    categoryText: '#633806',
    readTime: 5,
    publishedAt: '2025-05-08',
    relatedTool: 'favicon-generator',
    relatedToolName: 'Favicon Generator',
    lang: 'en',
    keywords: ['favicon guide', 'favicon sizes', 'favicon formats', 'ico vs png', 'apple touch icon', 'pwa icon', 'add favicon website'],
  },

  // OpenSSL & Cert
  {
    slug: 'x509-certificate-guide',
    title: 'X.509 Certificates Explained: How to Read and Inspect SSL Certificate Details',
    description: 'Learn how to read an X.509 SSL certificate — subject, issuer, SANs, validity dates, key size, signature algorithm, and fingerprints. Includes practical examples for verifying certificates before deployment.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-05-09',
    relatedTool: 'certificate-decoder',
    relatedToolName: 'Certificate Decoder',
    lang: 'en',
    keywords: ['x509 certificate', 'ssl certificate details', 'certificate decoder', 'san ssl', 'certificate fingerprint', 'read ssl certificate'],
  },

  // Thai Tools
  {
    slug: 'thai-number-writing-guide',
    title: 'วิธีอ่านและเขียนตัวเลขภาษาไทย: หลักพัน หมื่น แสน ล้าน',
    description: 'คู่มือการอ่านและเขียนตัวเลขภาษาไทยทุกหลัก ตั้งแต่หน่วยถึงพันล้าน พร้อมตัวอย่างการแปลงตัวเลขเป็นคำอ่าน กฎพิเศษ ยี่สิบ เอ็ด และการใช้งานในเอกสารราชการ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 5,
    publishedAt: '2025-05-10',
    relatedTool: 'thai-number-to-text',
    relatedToolName: 'แปลงตัวเลขเป็นคำอ่านภาษาไทย',
    lang: 'th',
    keywords: ['ตัวเลขภาษาไทย', 'อ่านตัวเลขภาษาไทย', 'เขียนตัวเลขเป็นคำ', 'หลักพัน หมื่น แสน ล้าน', 'แปลงเลขเป็นคำ'],
  },
  // ============================================================
  // BATCH 3 — เพิ่มใน articles array ใน lib/articles.ts
  // ============================================================
  // ประเภท: Comparison (7) + Error/Fix (5) + How-to (3)
  // ทั้งหมด English — ไม่ tie กับ tool เฉพาะ
  // publishedAt: 2025-05-11 → 2025-05-25
  // ============================================================

    // ── Comparison articles ──────────────────────────────────────

    {
      slug: 'https-vs-http',
      title: 'HTTPS vs HTTP: What\'s the Difference and Why It Matters',
      description: 'Understand the real difference between HTTP and HTTPS — how TLS encryption works, what data is protected, performance impact, and why every website needs HTTPS today.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 6,
      publishedAt: '2025-05-11',
      lang: 'en',
      keywords: ['https vs http', 'http https difference', 'what is https', 'tls encryption', 'https security'],
    },
    {
      slug: 'jwt-vs-session-auth',
      title: 'JWT vs Session-based Authentication: Which Should You Use?',
      description: 'A practical comparison of JWT and session-based authentication — stateless vs stateful, scalability, security tradeoffs, token storage risks, and when to choose each for your application.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 8,
      publishedAt: '2025-05-12',
      relatedTool: 'jwt-decoder',
      relatedToolName: 'JWT Decoder',
      lang: 'en',
      keywords: ['jwt vs session', 'session authentication', 'jwt authentication', 'stateless auth', 'token vs session'],
    },
    {
      slug: 'rsa-vs-ecdsa-vs-ed25519',
      title: 'RSA vs ECDSA vs Ed25519: Choosing the Right Key Algorithm',
      description: 'Compare RSA, ECDSA, and Ed25519 key algorithms — key sizes, performance, security level, browser support, and which to use for SSH keys, SSL certificates, and JWT signing.',
      category: 'OpenSSL & Cert',
      categoryColor: '#eef6ff',
      categoryText: '#1D4ED8',
      readTime: 7,
      publishedAt: '2025-05-13',
      relatedTool: 'rsa-key-generator',
      relatedToolName: 'RSA Key Generator',
      lang: 'en',
      keywords: ['rsa vs ecdsa', 'ed25519 vs rsa', 'ssh key algorithm', 'ecdsa vs rsa performance', 'key algorithm comparison'],
    },
    {
      slug: 'json-vs-xml',
      title: 'JSON vs XML: Differences, Use Cases, and When to Use Each',
      description: 'A thorough comparison of JSON and XML — syntax, verbosity, data types, namespaces, schema validation, parsing speed, and which format fits REST APIs, SOAP services, and configuration files.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 7,
      publishedAt: '2025-05-14',
      relatedTool: 'json-formatter',
      relatedToolName: 'JSON Formatter',
      lang: 'en',
      keywords: ['json vs xml', 'xml vs json', 'json xml difference', 'rest api json xml', 'data format comparison'],
    },
    {
      slug: 'png-vs-jpg-vs-webp',
      title: 'PNG vs JPG vs WebP: Which Image Format Should You Use?',
      description: 'Compare PNG, JPG, and WebP image formats — compression type, file size, quality, transparency support, browser compatibility, and the right format for photos, icons, and web graphics.',
      category: 'File & Image',
      categoryColor: '#faeeda',
      categoryText: '#633806',
      readTime: 6,
      publishedAt: '2025-05-15',
      relatedTool: 'image-compressor',
      relatedToolName: 'Image Compressor',
      lang: 'en',
      keywords: ['png vs jpg', 'webp vs png', 'jpg vs png vs webp', 'image format comparison', 'best image format web'],
    },
    {
      slug: 'sha256-vs-bcrypt-vs-argon2',
      title: 'SHA-256 vs bcrypt vs Argon2: Password Hashing Compared',
      description: 'Understand why SHA-256 is wrong for passwords and how bcrypt and Argon2 differ — work factors, memory hardness, GPU resistance, and which hashing algorithm to use in 2025.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 7,
      publishedAt: '2025-05-16',
      relatedTool: 'hash-generator',
      relatedToolName: 'Hash Generator',
      lang: 'en',
      keywords: ['sha256 vs bcrypt', 'bcrypt vs argon2', 'password hashing', 'argon2 bcrypt comparison', 'secure password hash'],
    },
    {
      slug: 'lets-encrypt-vs-paid-ssl',
      title: 'Let\'s Encrypt vs Paid SSL Certificates: What\'s the Difference?',
      description: 'Compare free Let\'s Encrypt certificates with paid SSL — validation types (DV, OV, EV), wildcard support, warranty, browser trust, auto-renewal, and when you actually need to pay for SSL.',
      category: 'OpenSSL & Cert',
      categoryColor: '#eef6ff',
      categoryText: '#1D4ED8',
      readTime: 6,
      publishedAt: '2025-05-17',
      relatedTool: 'csr-generator',
      relatedToolName: 'CSR Generator',
      lang: 'en',
      keywords: ["let's encrypt vs paid ssl", 'free ssl certificate', 'ssl certificate comparison', 'dv ov ev certificate', 'lets encrypt wildcard'],
    },

    // ── Error / Troubleshooting articles ─────────────────────────

    {
      slug: 'err-ssl-protocol-error',
      title: 'ERR_SSL_PROTOCOL_ERROR: Causes and How to Fix It',
      description: 'Fix ERR_SSL_PROTOCOL_ERROR in Chrome and other browsers — covers expired certificates, TLS version mismatches, self-signed cert issues, localhost HTTPS, and server misconfiguration.',
      category: 'OpenSSL & Cert',
      categoryColor: '#eef6ff',
      categoryText: '#1D4ED8',
      readTime: 6,
      publishedAt: '2025-05-18',
      relatedTool: 'certificate-decoder',
      relatedToolName: 'Certificate Decoder',
      lang: 'en',
      keywords: ['err_ssl_protocol_error', 'ssl protocol error fix', 'err ssl protocol error chrome', 'ssl error fix', 'https ssl error'],
    },
    {
      slug: 'invalid-json-fix',
      title: 'Invalid JSON: How to Find and Fix JSON Syntax Errors',
      description: 'Diagnose and fix invalid JSON errors — trailing commas, unquoted keys, single quotes, undefined values, comments, and circular references. Includes error messages decoded with line-by-line fixes.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 5,
      publishedAt: '2025-05-19',
      relatedTool: 'json-formatter',
      relatedToolName: 'JSON Formatter',
      lang: 'en',
      keywords: ['invalid json', 'json syntax error', 'fix json error', 'json parse error', 'unexpected token json'],
    },
    {
      slug: 'jwt-expired-error',
      title: 'JWT Expired: What It Means and How to Handle Token Expiry',
      description: 'Understand JWT expiry — what the exp claim means, why tokens expire, how to handle TokenExpiredError in Node.js and Python, refresh token patterns, and best practices for token lifetime.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 6,
      publishedAt: '2025-05-20',
      relatedTool: 'jwt-decoder',
      relatedToolName: 'JWT Decoder',
      lang: 'en',
      keywords: ['jwt expired', 'jwt token expired', 'tokenexpirederror', 'jwt refresh token', 'jwt expiry handling'],
    },
    {
      slug: 'cors-error-fix',
      title: 'CORS Error Fix: Access-Control-Allow-Origin Explained',
      description: 'Fix CORS errors step by step — what Access-Control-Allow-Origin means, why the browser blocks requests, how to configure CORS in Express, Nginx, and FastAPI, and how preflight requests work.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 7,
      publishedAt: '2025-05-21',
      lang: 'en',
      keywords: ['cors error fix', 'access-control-allow-origin', 'cors policy', 'fix cors', 'cors express nginx'],
    },
    {
      slug: '413-request-entity-too-large',
      title: '413 Request Entity Too Large: How to Fix It in Nginx and Apache',
      description: 'Fix 413 Request Entity Too Large errors — what causes them, how to increase client_max_body_size in Nginx and LimitRequestBody in Apache, and how to handle large file uploads in Node.js and PHP.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 5,
      publishedAt: '2025-05-22',
      lang: 'en',
      keywords: ['413 request entity too large', '413 error nginx', 'client_max_body_size', 'fix 413 error', 'nginx file upload size'],
    },

    // ── How-to guides ─────────────────────────────────────────────

    {
      slug: 'nginx-ssl-lets-encrypt',
      title: 'How to Set Up HTTPS on Nginx with Let\'s Encrypt',
      description: 'Step-by-step guide to enabling HTTPS on Nginx using Let\'s Encrypt and Certbot — installation, certificate generation, auto-renewal, HTTP to HTTPS redirect, and security header configuration.',
      category: 'OpenSSL & Cert',
      categoryColor: '#eef6ff',
      categoryText: '#1D4ED8',
      readTime: 9,
      publishedAt: '2025-05-23',
      relatedTool: 'openssl-command-builder',
      relatedToolName: 'OpenSSL Command Builder',
      lang: 'en',
      keywords: ['nginx ssl lets encrypt', 'certbot nginx', 'https nginx setup', 'lets encrypt nginx', 'nginx ssl certificate'],
    },
    {
      slug: 'linux-file-permissions-explained',
      title: 'Linux File Permissions Explained: chmod, chown, and ls -l',
      description: 'Master Linux file permissions — how to read rwxr-xr-x notation, what octal 755 and 644 mean, how chmod and chown work, setuid/setgid bits, umask, and common permission mistakes to avoid.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 8,
      publishedAt: '2025-05-24',
      relatedTool: 'chmod-calculator',
      relatedToolName: 'Chmod Calculator',
      lang: 'en',
      keywords: ['linux file permissions', 'chmod explained', 'linux permissions 755 644', 'chown command', 'ls -l permissions'],
    },
    {
      slug: 'linux-cron-job-setup',
      title: 'Linux Cron Job: A Practical Setup and Debugging Guide',
      description: 'Set up and debug Linux cron jobs correctly — crontab syntax, environment variables in cron, output logging, common reasons cron jobs fail silently, and how to use systemd timers as an alternative.',
      category: 'Dev / IT',
      categoryColor: '#eeedfe',
      categoryText: '#3c3489',
      readTime: 8,
      publishedAt: '2025-05-25',
      relatedTool: 'cron-builder',
      relatedToolName: 'Cron Builder',
      lang: 'en',
      keywords: ['linux cron job', 'crontab setup', 'cron job debugging', 'cron not running', 'crontab environment variables'],
    },

  // ============================================================
  // BATCH 4 — Standalone informational (6 EN) + Thai-specific (4)
  // publishedAt: 2025-05-26 → 2025-06-04
  // ============================================================

  {
    slug: 'what-is-ssl-tls',
    title: 'What is SSL/TLS? How HTTPS Actually Works',
    description: 'A clear, complete explanation of SSL and TLS — what they are, how the TLS handshake works, what certificates do, and why HTTPS protects your data in transit. No cryptography degree required.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-05-26',
    lang: 'en' as const,
    keywords: ['what is ssl tls', 'how https works', 'tls handshake explained', 'ssl explained', 'https ssl difference'],
  },
  {
    slug: 'public-key-cryptography-explained',
    title: 'Public Key Cryptography Explained Simply',
    description: 'Understand public key cryptography without the math — how public and private keys work together, what asymmetric encryption means, digital signatures, key exchange, and real-world uses in HTTPS, SSH, and JWT.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-05-27',
    lang: 'en' as const,
    keywords: ['public key cryptography', 'asymmetric encryption explained', 'public private key explained', 'digital signature explained', 'key exchange'],
  },
  {
    slug: 'http-status-codes-guide',
    title: 'HTTP Status Codes: A Complete Reference (200, 301, 404, 500…)',
    description: 'Every HTTP status code explained — 1xx informational, 2xx success, 3xx redirects, 4xx client errors, and 5xx server errors. Includes when each code should be used and common mistakes developers make.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 9,
    publishedAt: '2025-05-28',
    lang: 'en' as const,
    keywords: ['http status codes', 'http 404 explained', 'http 500 error', '301 redirect', 'http response codes complete'],
  },
  {
    slug: 'dns-explained',
    title: 'How DNS Works: From Domain Name to IP Address',
    description: 'Step-by-step explanation of how DNS resolves a domain name to an IP address — recursive resolvers, root servers, authoritative name servers, TTL, DNS record types (A, CNAME, MX, TXT), and DNS propagation.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-05-29',
    lang: 'en' as const,
    keywords: ['how dns works', 'dns explained', 'dns resolution', 'dns record types', 'domain name system'],
  },
  {
    slug: 'api-authentication-methods',
    title: 'API Authentication Methods: API Keys, OAuth 2.0, and JWT Compared',
    description: 'Compare the three main API authentication methods — API Keys, OAuth 2.0, and JWT — with their strengths, weaknesses, security implications, and which to choose for public APIs, mobile apps, and service-to-service communication.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-05-30',
    relatedTool: 'jwt-decoder',
    relatedToolName: 'JWT Decoder',
    lang: 'en' as const,
    keywords: ['api authentication', 'api key vs oauth', 'oauth vs jwt', 'api security methods', 'rest api authentication'],
  },
  {
    slug: 'linux-permissions-cheatsheet',
    title: 'Linux File Permissions Cheatsheet: chmod, chown, umask',
    description: 'A practical Linux file permissions cheatsheet covering chmod numeric and symbolic modes, common permission patterns (755, 644, 700), chown and chgrp, umask defaults, and special bits (setuid, setgid, sticky bit).',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-31',
    relatedTool: 'chmod-calculator',
    relatedToolName: 'Chmod Calculator',
    lang: 'en' as const,
    keywords: ['linux permissions cheatsheet', 'chmod cheatsheet', 'linux file permissions reference', 'umask explained', 'chown chgrp guide'],
  },
  {
    slug: 'pdpa-thailand-developers',
    title: 'PDPA Thailand for Developers: What You Need to Build Compliant Apps',
    description: 'A practical guide to Thailand\'s Personal Data Protection Act (PDPA) for software developers — what counts as personal data, consent requirements, data subject rights, retention policies, and how to implement compliance in your app.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 9,
    publishedAt: '2025-06-01',
    lang: 'en' as const,
    keywords: ['pdpa thailand developers', 'pdpa compliance guide', 'thailand data protection', 'pdpa personal data', 'pdpa app development'],
  },
  {
    slug: 'thai-vat-guide',
    title: 'คู่มือ VAT สำหรับผู้ประกอบการไทย: ออกใบกำกับภาษีให้ถูกต้อง',
    description: 'คู่มือ VAT ฉบับครบสำหรับเจ้าของธุรกิจและผู้ประกอบการไทย ครอบคลุมการจดทะเบียน VAT เกณฑ์รายได้ ประเภทใบกำกับภาษี รายการที่ต้องมี และข้อผิดพลาดที่พบบ่อยในการออกใบกำกับภาษี',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 8,
    publishedAt: '2025-06-02',
    relatedTool: 'thai-vat-calculator',
    relatedToolName: 'Thai VAT Calculator',
    lang: 'th' as const,
    keywords: ['vat ไทย', 'ใบกำกับภาษี', 'จดทะเบียน vat', 'ภาษีมูลค่าเพิ่ม ผู้ประกอบการ', 'thai vat guide'],
  },
  {
    slug: 'thai-company-tax-id',
    title: 'เลขประจำตัวผู้เสียภาษี (Tax ID) ไทย: ความหมาย โครงสร้าง และวิธีตรวจสอบ',
    description: 'อธิบายโครงสร้างเลขประจำตัวผู้เสียภาษี 13 หลักของไทย ความแตกต่างระหว่าง Tax ID บุคคลธรรมดาและนิติบุคคล วิธีตรวจสอบเลขผ่านระบบกรมสรรพากร และการนำไปใช้ในเอกสารทางธุรกิจ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 5,
    publishedAt: '2025-06-03',
    relatedTool: 'thai-id-validator',
    relatedToolName: 'Thai ID Validator',
    lang: 'th' as const,
    keywords: ['เลขประจำตัวผู้เสียภาษี', 'tax id ไทย', 'เลขนิติบุคคล', 'ตรวจสอบเลขผู้เสียภาษี', 'เลข 13 หลัก กรมสรรพากร'],
  },
  {
    slug: 'https-ssl-pdpa-thai-business',
    title: 'ธุรกิจออนไลน์ไทยต้องมี SSL ไหม? PDPA กับความปลอดภัยข้อมูลลูกค้า',
    description: 'ตอบข้อสงสัยสำหรับเจ้าของธุรกิจออนไลน์ไทย ว่า HTTPS/SSL จำเป็นแค่ไหน เชื่อมโยงกับ PDPA อย่างไร ผลกระทบต่อ SEO และความน่าเชื่อถือ พร้อมขั้นตอนติดตั้ง SSL ราคาถูก/ฟรีสำหรับเว็บไซต์ธุรกิจ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 6,
    publishedAt: '2025-06-04',
    lang: 'th' as const,
    keywords: ['ssl ธุรกิจออนไลน์ไทย', 'https pdpa', 'ssl ฟรี ไทย', 'ติดตั้ง ssl เว็บไซต์', 'pdpa ความปลอดภัยข้อมูล'],
  },

  // ============================================================
  // BATCH 5 — Developer Career, Security & Privacy, Thai Dev/Business
  // publishedAt: 2025-06-05 → 2025-06-16
  // ============================================================

  {
    slug: 'best-free-developer-tools-2025',
    title: 'Best Free Developer Tools in 2025: A Curated List',
    description: 'A curated list of the best free tools every developer should know — from JSON formatters and regex testers to terminal emulators, API clients, and browser extensions. No fluff, just tools that solve real problems.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-06-05',
    lang: 'en' as const,
    keywords: ['best free developer tools', 'developer tools 2025', 'free tools for developers', 'developer productivity tools', 'web developer tools'],
  },
  {
    slug: 'api-testing-guide',
    title: 'How to Test APIs: curl, Postman, and Other Tools Compared',
    description: 'A practical guide to API testing — how to use curl for quick requests, Postman for organized collections, and other HTTP clients. Covers GET/POST/PUT/DELETE requests, headers, authentication, and reading API responses.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-06-06',
    lang: 'en' as const,
    keywords: ['api testing guide', 'curl api testing', 'postman guide', 'how to test rest api', 'api client tools'],
  },
  {
    slug: 'vps-vs-shared-hosting',
    title: 'VPS vs Shared Hosting: Which Should Developers Choose?',
    description: 'A developer-focused comparison of VPS and shared hosting — performance, control, pricing, scaling, use cases, and when to upgrade. Includes real-world guidance on choosing between managed VPS, cloud VMs, and Cloudflare Pages.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-06-07',
    lang: 'en' as const,
    keywords: ['vps vs shared hosting', 'vps vs shared hosting developers', 'when to use vps', 'cloud hosting comparison', 'vps shared hosting difference'],
  },
  {
    slug: 'cloudflare-free-tier-guide',
    title: 'Cloudflare Free Tier: What You Get and How to Set It Up',
    description: 'Everything included in Cloudflare\'s free plan — CDN, DDoS protection, SSL, DNS, Pages, Workers, R2 storage, and analytics. Step-by-step setup guide for pointing your domain to Cloudflare and deploying a static site.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-06-08',
    lang: 'en' as const,
    keywords: ['cloudflare free tier', 'cloudflare free plan', 'cloudflare pages free', 'cloudflare setup guide', 'cloudflare cdn free'],
  },
  {
    slug: 'https-everywhere-guide',
    title: 'Why Every Website Needs HTTPS (Even Static Sites)',
    description: 'The case for HTTPS on every website — browser warnings, SEO ranking signals, PDPA/GDPR compliance, mixed content issues, and how free SSL from Let\'s Encrypt and Cloudflare makes there is no excuse not to have it.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 6,
    publishedAt: '2025-06-09',
    lang: 'en' as const,
    keywords: ['why https matters', 'https static site', 'https seo ranking', 'free ssl certificate', 'http to https migration'],
  },
  {
    slug: 'common-web-security-mistakes',
    title: '10 Common Web Security Mistakes Developers Make (And How to Fix Them)',
    description: 'The most common web security mistakes — hardcoded secrets in code, missing HTTPS, weak password storage, no rate limiting, open CORS, verbose error messages, missing security headers, and more — with concrete fixes for each.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 10,
    publishedAt: '2025-06-10',
    lang: 'en' as const,
    keywords: ['web security mistakes', 'common security vulnerabilities', 'developer security mistakes', 'web app security', 'owasp top 10 explained'],
  },
  {
    slug: 'data-encryption-explained',
    title: 'Data Encryption Explained: At Rest vs In Transit',
    description: 'Understand the two main types of data encryption — encryption at rest (databases, disks, backups) and encryption in transit (HTTPS, TLS, VPN). Covers AES, symmetric vs asymmetric encryption, and practical implementation tips.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-06-11',
    lang: 'en' as const,
    keywords: ['encryption at rest vs in transit', 'data encryption explained', 'aes encryption', 'database encryption', 'tls encryption transit'],
  },
  {
    slug: 'two-factor-authentication-guide',
    title: 'Two-Factor Authentication (2FA): Types, How It Works, and Best Practices',
    description: 'Everything about 2FA — TOTP authenticator apps, SMS codes, hardware keys (FIDO2/WebAuthn), backup codes, and why SMS 2FA is weaker than app-based 2FA. Includes implementation guidance for developers adding 2FA to apps.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-06-12',
    lang: 'en' as const,
    keywords: ['two factor authentication', '2fa guide', 'totp explained', 'authenticator app', 'webauthn fido2 explained'],
  },
  {
    slug: 'thai-developer-salary-guide',
    title: 'เงินเดือน Developer ไทย 2568: ตำแหน่งไหนได้เท่าไหร่?',
    description: 'รวมข้อมูลเงินเดือน Developer ในไทยปี 2568 แยกตามตำแหน่ง ประสบการณ์ และประเภทบริษัท ตั้งแต่ Junior Frontend ถึง Senior DevOps/Cloud รวมถึง Freelance Rate และเงินเดือน Remote งานต่างประเทศ',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-06-13',
    lang: 'th' as const,
    keywords: ['เงินเดือน developer ไทย', 'เงินเดือน programmer ไทย 2568', 'เงินเดือน frontend backend', 'developer salary thailand', 'เงินเดือน it ไทย'],
  },
  {
    slug: 'freelance-tax-thailand',
    title: 'Freelance ไทยต้องเสียภาษีอะไรบ้าง? คู่มือครบจบสำหรับฟรีแลนซ์',
    description: 'คู่มือภาษีสำหรับ Freelance ไทยและ Developer อิสระ ครอบคลุมภาษีเงินได้มาตรา 40(2) ค่าใช้จ่ายเหมา 50% วิธียื่นภาษีออนไลน์ VAT สำหรับ Freelance ที่มีรายได้เกินเกณฑ์ และการรับเงินจากต่างประเทศ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 9,
    publishedAt: '2025-06-14',
    relatedTool: 'thai-tax-calculator',
    relatedToolName: 'คำนวณภาษีเงินได้บุคคลธรรมดา 2568',
    lang: 'th' as const,
    keywords: ['ภาษี freelance ไทย', 'freelance เสียภาษีอย่างไร', 'ภาษีมาตรา 40(2)', 'ยื่นภาษี freelance', 'developer freelance ภาษี'],
  },
  {
    slug: 'open-source-license-guide',
    title: 'Open Source Licenses Explained: MIT, Apache, GPL, and When They Matter',
    description: 'A clear guide to open source licenses — what MIT, Apache 2.0, GPL v2/v3, LGPL, and BSD licenses allow and restrict. Covers commercial use, attribution requirements, copyleft implications, and how to choose a license for your project.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-06-15',
    lang: 'en' as const,
    keywords: ['open source license guide', 'mit vs apache vs gpl', 'open source license comparison', 'copyleft explained', 'choose open source license'],
  },
  {
    slug: 'git-workflow-guide',
    title: 'Git Workflow Guide: Branching Strategies for Solo and Team Projects',
    description: 'Practical Git workflow strategies — trunk-based development, GitHub Flow, Gitflow, feature branches, and when to use each. Covers commit message conventions, PR best practices, merge vs rebase, and tagging releases.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-06-16',
    lang: 'en' as const,
    keywords: ['git workflow', 'git branching strategy', 'github flow', 'gitflow explained', 'git merge vs rebase'],
  },
]

export const getArticle = (slug: string) => articles.find(a => a.slug === slug)

export const articlesByCategory = (category: string) =>
  articles.filter(a => a.category === category)