export interface Article {
  slug: string
  title: string
  description: string
  category: string
  categoryColor: string
  categoryText: string
  readTime: number
  publishedAt: string
  relatedTool?: string
  relatedToolName?: string
  lang: 'en' | 'th'
  keywords: string[]
}

export const articles: Article[] = [
  // Dev / IT
  {
    slug: 'what-is-jwt',
    title: 'What is JWT? Understanding JSON Web Tokens',
    description: 'A complete guide to JSON Web Tokens — how they work, what the header, payload, and signature mean, and when to use them in your applications.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-04-01',
    relatedTool: 'jwt-decoder',
    relatedToolName: 'JWT Decoder',
    lang: 'en',
    keywords: ['jwt', 'json web token', 'jwt tutorial', 'jwt explained', 'jwt header payload signature'],
  },
  {
    slug: 'base64-encoding-explained',
    title: 'Base64 Encoding Explained: What It Is and When to Use It',
    description: 'Learn what Base64 encoding is, how it works, why it exists, and common use cases including JWT, data URIs, and API payloads.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-04-02',
    relatedTool: 'base64-encode-decode',
    relatedToolName: 'Base64 Encode / Decode',
    lang: 'en',
    keywords: ['base64 encoding', 'base64 explained', 'what is base64', 'base64 use cases'],
  },
  {
    slug: 'cidr-subnetting-guide',
    title: 'CIDR Notation and Subnetting: A Complete Guide',
    description: 'Master CIDR notation and subnetting. Learn how to calculate network addresses, host ranges, broadcast addresses, and usable IPs from any CIDR block.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 8,
    publishedAt: '2025-04-03',
    relatedTool: 'cidr-calculator',
    relatedToolName: 'CIDR Calculator',
    lang: 'en',
    keywords: ['cidr notation', 'subnetting guide', 'cidr explained', 'subnet calculator', 'ip addressing'],
  },
  {
    slug: 'regex-guide-for-developers',
    title: 'Regular Expressions (Regex) Guide for Developers',
    description: 'A practical regex guide with real examples. Learn anchors, character classes, quantifiers, groups, and lookaheads — with patterns you can use today.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 9,
    publishedAt: '2025-04-04',
    relatedTool: 'regex-tester',
    relatedToolName: 'Regex Tester',
    lang: 'en',
    keywords: ['regex tutorial', 'regular expressions guide', 'regex examples', 'learn regex'],
  },
  {
    slug: 'hash-functions-md5-sha256-sha512',
    title: 'MD5 vs SHA-1 vs SHA-256 vs SHA-512: Hash Functions Explained',
    description: 'Understand cryptographic hash functions, the differences between MD5, SHA-1, SHA-256, and SHA-512, and which one to use for your security needs.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-04-05',
    relatedTool: 'hash-generator',
    relatedToolName: 'Hash Generator',
    lang: 'en',
    keywords: ['md5 vs sha256', 'hash functions explained', 'cryptographic hash', 'sha256 sha512 difference'],
  },
  {
    slug: 'cron-expression-guide',
    title: 'Cron Expression Guide: Schedule Jobs Like a Pro',
    description: 'Master cron syntax with this complete guide. Learn every field, special characters, common patterns, and how to schedule jobs on Linux, AWS, and Kubernetes.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-04-06',
    relatedTool: 'cron-builder',
    relatedToolName: 'Cron Builder',
    lang: 'en',
    keywords: ['cron expression', 'cron syntax', 'cron job guide', 'cron schedule'],
  },
  {
    slug: 'uuid-guide',
    title: 'UUID Explained: v1, v4, v5 and When to Use Each',
    description: 'Everything you need to know about UUIDs — the difference between v1, v4, and v5, how they are generated, and best practices for using them in databases and APIs.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-04-07',
    relatedTool: 'uuid-generator',
    relatedToolName: 'UUID Generator',
    lang: 'en',
    keywords: ['uuid explained', 'uuid v4 vs v1', 'what is uuid', 'uuid best practices'],
  },
  {
    slug: 'unix-timestamp-explained',
    title: 'Unix Timestamps Explained: Epoch Time, Seconds vs Milliseconds',
    description: 'Learn what Unix timestamps are, how epoch time works, the difference between seconds and milliseconds timestamps, and how to convert them in any programming language.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-04-08',
    relatedTool: 'unix-timestamp',
    relatedToolName: 'Unix Timestamp Converter',
    lang: 'en',
    keywords: ['unix timestamp', 'epoch time explained', 'unix time seconds milliseconds'],
  },
  {
    slug: 'json-yaml-comparison',
    title: 'JSON vs YAML: Differences, Use Cases, and When to Use Each',
    description: 'A detailed comparison of JSON and YAML formats — syntax differences, readability, use cases in DevOps and APIs, and how to convert between them.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-04-09',
    relatedTool: 'json-to-yaml',
    relatedToolName: 'JSON ↔ YAML Converter',
    lang: 'en',
    keywords: ['json vs yaml', 'yaml vs json', 'json yaml difference', 'when to use yaml'],
  },
  // OpenSSL & Cert
  {
    slug: 'ssl-certificate-types-explained',
    title: 'SSL Certificate Types Explained: PEM, DER, PKCS12, and More',
    description: 'A complete guide to SSL certificate formats — PEM, DER, PKCS12/PFX, and PKCS8. Learn what each format is, when to use it, and how to convert between them.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-04-10',
    relatedTool: 'pem-der-converter',
    relatedToolName: 'PEM ↔ DER Converter',
    lang: 'en',
    keywords: ['ssl certificate formats', 'pem vs der', 'pkcs12 explained', 'ssl cert types'],
  },
  {
    slug: 'self-signed-certificate-guide',
    title: 'How to Create a Self-signed SSL Certificate for Local Development',
    description: 'Step-by-step guide to generating self-signed SSL certificates for localhost, development environments, and internal services using OpenSSL and browser tools.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 8,
    publishedAt: '2025-04-11',
    relatedTool: 'self-signed-cert',
    relatedToolName: 'Self-signed Cert Generator',
    lang: 'en',
    keywords: ['self signed certificate', 'localhost ssl', 'development ssl certificate', 'openssl self signed'],
  },
  {
    slug: 'what-is-csr',
    title: 'What is a CSR? How to Generate and Submit a Certificate Signing Request',
    description: 'Learn what a Certificate Signing Request (CSR) is, what information it contains, how to generate one, and how to submit it to a Certificate Authority to get an SSL certificate.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-04-12',
    relatedTool: 'csr-generator',
    relatedToolName: 'CSR Generator',
    lang: 'en',
    keywords: ['what is csr', 'certificate signing request', 'how to generate csr', 'ssl csr guide'],
  },
  {
    slug: 'tls-versions-explained',
    title: 'TLS 1.0, 1.1, 1.2, and 1.3: Differences and Why Versions Matter',
    description: 'Understand the differences between TLS 1.0, 1.1, 1.2, and 1.3. Learn why older versions are deprecated, what security improvements TLS 1.3 brings, and how to check what your server supports.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-04-13',
    relatedTool: 'openssl-command-builder',
    relatedToolName: 'OpenSSL Command Builder',
    lang: 'en',
    keywords: ['tls versions', 'tls 1.2 vs 1.3', 'ssl tls differences', 'tls explained'],
  },
  {
    slug: 'rsa-encryption-explained',
    title: 'RSA Encryption Explained: Public Keys, Private Keys, and How It Works',
    description: 'A clear explanation of RSA asymmetric encryption — how public and private keys work, key sizes (1024 vs 2048 vs 4096-bit), digital signatures, and practical use cases.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 8,
    publishedAt: '2025-04-14',
    relatedTool: 'rsa-key-generator',
    relatedToolName: 'RSA Key Generator',
    lang: 'en',
    keywords: ['rsa encryption', 'public private key', 'asymmetric encryption', 'rsa explained'],
  },
  // Thai Tools (Thai language)
  {
    slug: 'thai-income-tax-2568-guide',
    title: 'วิธีคำนวณภาษีเงินได้บุคคลธรรมดา 2568 พร้อมค่าลดหย่อนครบทุกรายการ',
    description: 'คู่มือคำนวณภาษีเงินได้บุคคลธรรมดาปี 2568 ครบถ้วน ตั้งแต่ประเภทเงินได้ ค่าใช้จ่าย ค่าลดหย่อนทุกรายการ อัตราภาษีขั้นบันได พร้อมตัวอย่างการคำนวณ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 10,
    publishedAt: '2025-04-15',
    relatedTool: 'thai-tax-calculator',
    relatedToolName: 'คำนวณภาษีเงินได้บุคคลธรรมดา 2568',
    lang: 'th',
    keywords: ['ภาษีเงินได้บุคคลธรรมดา 2568', 'คำนวณภาษี 2568', 'ลดหย่อนภาษี 2568', 'อัตราภาษีบุคคลธรรมดา'],
  },
  {
    slug: 'thai-baht-to-words-guide',
    title: 'วิธีเขียนจำนวนเงินเป็นตัวอักษรภาษาไทยบนเช็คให้ถูกต้อง',
    description: 'คู่มือการเขียนจำนวนเงินเป็นตัวอักษรภาษาไทยสำหรับเขียนเช็ค ใบสำคัญจ่าย และเอกสารทางกฎหมาย พร้อมตัวอย่างและข้อควรระวัง',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 5,
    publishedAt: '2025-04-16',
    relatedTool: 'thai-baht-to-words',
    relatedToolName: 'จำนวนเงินบาทเป็นตัวอักษร',
    lang: 'th',
    keywords: ['เขียนเช็คภาษาไทย', 'จำนวนเงินเป็นตัวอักษร', 'เขียนตัวเลขเป็นคำ', 'บาทเป็นตัวอักษร'],
  },
  {
    slug: 'thai-date-converter-guide',
    title: 'พ.ศ. กับ ค.ศ. ต่างกันอย่างไร? วิธีแปลงวันที่ไทยและสากล',
    description: 'อธิบายความแตกต่างระหว่างปีพุทธศักราช (พ.ศ.) และคริสต์ศักราช (ค.ศ.) สูตรการแปลง และวิธีใช้งานในเอกสารราชการและธุรกิจระหว่างประเทศ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 4,
    publishedAt: '2025-04-17',
    relatedTool: 'thai-date-converter',
    relatedToolName: 'Thai Date Converter',
    lang: 'th',
    keywords: ['พ.ศ. ค.ศ. ต่างกันอย่างไร', 'แปลงวันที่ไทย', 'พุทธศักราช คริสต์ศักราช', 'แปลงปี พ.ศ.'],
  },
  // File & Image
  {
    slug: 'image-compression-guide',
    title: 'Image Compression Guide: Reduce File Size Without Losing Quality',
    description: 'Learn how image compression works, the difference between lossy and lossless compression, optimal quality settings, and when to use JPG, PNG, or WebP for your website.',
    category: 'File & Image',
    categoryColor: '#faeeda',
    categoryText: '#633806',
    readTime: 6,
    publishedAt: '2025-04-18',
    relatedTool: 'image-compressor',
    relatedToolName: 'Image Compressor',
    lang: 'en',
    keywords: ['image compression', 'compress images', 'jpg vs png vs webp', 'image optimization'],
  },
  {
    slug: 'qr-code-guide',
    title: 'QR Codes Explained: How They Work and Best Practices',
    description: 'Everything about QR codes — how they store data, error correction levels, size recommendations, and best practices for generating QR codes that scan reliably.',
    category: 'File & Image',
    categoryColor: '#faeeda',
    categoryText: '#633806',
    readTime: 5,
    publishedAt: '2025-04-19',
    relatedTool: 'qr-code-generator',
    relatedToolName: 'QR Code Generator',
    lang: 'en',
    keywords: ['qr code explained', 'how qr codes work', 'qr code best practices', 'qr code guide'],
  },

  // ── New articles (Batch 2) ────────────────────────────────────

  // Dev / IT
  {
    slug: 'json-formatting-guide',
    title: "JSON Formatting and Validation: A Developer's Complete Guide",
    description: 'Learn how to format, validate, and minify JSON correctly. Covers JSON syntax rules, common errors, indentation best practices, and when to minify vs pretty-print for APIs and config files.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-01',
    relatedTool: 'json-formatter',
    relatedToolName: 'JSON Formatter',
    lang: 'en',
    keywords: ['json format', 'json validation', 'json syntax', 'pretty print json', 'json minify', 'json best practices'],
  },
  {
    slug: 'url-encoding-explained',
    title: 'URL Encoding Explained: Percent-Encoding, encodeURI vs encodeURIComponent',
    description: 'Understand URL encoding (percent-encoding) — why it exists, how %20 and other sequences work, and the critical difference between encodeURI and encodeURIComponent in JavaScript.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-05-02',
    relatedTool: 'url-encode-decode',
    relatedToolName: 'URL Encode / Decode',
    lang: 'en',
    keywords: ['url encoding', 'percent encoding', 'encodeuri vs encodeuricomponent', 'url encode decode', 'url special characters'],
  },
  {
    slug: 'password-security-guide',
    title: 'Password Security Guide: What Makes a Strong Password and How to Generate One',
    description: 'Everything you need to know about password strength — entropy, character sets, length requirements, why password managers matter, and how cryptographically secure random generators work.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-03',
    relatedTool: 'password-generator',
    relatedToolName: 'Password Generator',
    lang: 'en',
    keywords: ['password security', 'strong password', 'password entropy', 'password generator', 'secure password tips'],
  },
  {
    slug: 'json-to-csv-guide',
    title: 'JSON to CSV Conversion: How to Export JSON Data for Excel and Google Sheets',
    description: 'Learn how to convert JSON arrays to CSV format for spreadsheets. Covers flattening nested objects, handling special characters, choosing delimiters, and converting CSV back to JSON for APIs.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 5,
    publishedAt: '2025-05-04',
    relatedTool: 'json-to-csv',
    relatedToolName: 'JSON ↔ CSV Converter',
    lang: 'en',
    keywords: ['json to csv', 'convert json to csv', 'json excel', 'csv format', 'json array csv'],
  },
  {
    slug: 'css-color-formats-explained',
    title: 'CSS Color Formats Explained: HEX, RGB, HSL, and When to Use Each',
    description: 'A complete guide to CSS color formats — how HEX, RGB, RGBA, HSL, and HSLA work, how to convert between them, and which format to use for web design, theming, and accessibility.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-05',
    relatedTool: 'color-converter',
    relatedToolName: 'Color Converter',
    lang: 'en',
    keywords: ['css color formats', 'hex vs rgb', 'hsl color', 'rgba explained', 'color converter css', 'web colors guide'],
  },
  {
    slug: 'markdown-guide',
    title: 'Markdown Guide: Complete Syntax Reference for Developers and Writers',
    description: 'Master Markdown syntax from basics to advanced features. Covers headings, bold, italic, tables, code blocks, links, images, GitHub Flavored Markdown (GFM), and tips for README files and documentation.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 7,
    publishedAt: '2025-05-06',
    relatedTool: 'markdown-preview',
    relatedToolName: 'Markdown Preview',
    lang: 'en',
    keywords: ['markdown guide', 'markdown syntax', 'markdown tutorial', 'github markdown', 'readme markdown', 'markdown cheatsheet'],
  },
  {
    slug: 'content-length-seo-guide',
    title: 'Content Length and SEO: How Many Words Do You Really Need?',
    description: 'Does word count affect SEO rankings? Learn what Google actually says about content length, optimal blog post length by type, character limits for meta tags and social media, and how to measure readability.',
    category: 'Dev / IT',
    categoryColor: '#eeedfe',
    categoryText: '#3c3489',
    readTime: 6,
    publishedAt: '2025-05-07',
    relatedTool: 'word-counter',
    relatedToolName: 'Word Counter',
    lang: 'en',
    keywords: ['content length seo', 'word count seo', 'ideal blog post length', 'character count', 'seo content guide'],
  },

  // File & Image
  {
    slug: 'favicon-guide',
    title: 'Favicon Guide: Sizes, Formats, and How to Add One to Your Website',
    description: 'Everything about favicons — all the sizes you need (16px to 512px), ICO vs PNG vs SVG formats, Apple touch icons, PWA icons, and exactly how to add favicon HTML tags to your site.',
    category: 'File & Image',
    categoryColor: '#faeeda',
    categoryText: '#633806',
    readTime: 5,
    publishedAt: '2025-05-08',
    relatedTool: 'favicon-generator',
    relatedToolName: 'Favicon Generator',
    lang: 'en',
    keywords: ['favicon guide', 'favicon sizes', 'favicon formats', 'ico vs png', 'apple touch icon', 'pwa icon', 'add favicon website'],
  },

  // OpenSSL & Cert
  {
    slug: 'x509-certificate-guide',
    title: 'X.509 Certificates Explained: How to Read and Inspect SSL Certificate Details',
    description: 'Learn how to read an X.509 SSL certificate — subject, issuer, SANs, validity dates, key size, signature algorithm, and fingerprints. Includes practical examples for verifying certificates before deployment.',
    category: 'OpenSSL & Cert',
    categoryColor: '#eef6ff',
    categoryText: '#1D4ED8',
    readTime: 7,
    publishedAt: '2025-05-09',
    relatedTool: 'certificate-decoder',
    relatedToolName: 'Certificate Decoder',
    lang: 'en',
    keywords: ['x509 certificate', 'ssl certificate details', 'certificate decoder', 'san ssl', 'certificate fingerprint', 'read ssl certificate'],
  },

  // Thai Tools
  {
    slug: 'thai-number-writing-guide',
    title: 'วิธีอ่านและเขียนตัวเลขภาษาไทย: หลักพัน หมื่น แสน ล้าน',
    description: 'คู่มือการอ่านและเขียนตัวเลขภาษาไทยทุกหลัก ตั้งแต่หน่วยถึงพันล้าน พร้อมตัวอย่างการแปลงตัวเลขเป็นคำอ่าน กฎพิเศษ ยี่สิบ เอ็ด และการใช้งานในเอกสารราชการ',
    category: 'Thai Tools',
    categoryColor: '#e1f5ee',
    categoryText: '#085041',
    readTime: 5,
    publishedAt: '2025-05-10',
    relatedTool: 'thai-number-to-text',
    relatedToolName: 'แปลงตัวเลขเป็นคำอ่านภาษาไทย',
    lang: 'th',
    keywords: ['ตัวเลขภาษาไทย', 'อ่านตัวเลขภาษาไทย', 'เขียนตัวเลขเป็นคำ', 'หลักพัน หมื่น แสน ล้าน', 'แปลงเลขเป็นคำ'],
  },
]

export const getArticle = (slug: string) => articles.find(a => a.slug === slug)

export const articlesByCategory = (category: string) =>
  articles.filter(a => a.category === category)