'use client'

export default function PasswordSecurityGuide() {
  return (
    <article className="prose-article">
      <p>
        Most people know weak passwords are dangerous — but few understand <em>why</em> a particular
        password is weak or exactly how attackers crack them. This guide explains password entropy,
        how random generators work, and practical advice for keeping accounts secure.
      </p>

      <h2>What Makes a Password Strong?</h2>
      <p>
        Password strength comes down to two factors: <strong>length</strong> and{' '}
        <strong>unpredictability</strong>. Longer passwords with larger character sets take
        exponentially more attempts to crack.
      </p>
      <p>
        The metric for this is <strong>entropy</strong>, measured in bits. A password with{' '}
        <em>n</em> bits of entropy would require up to 2<sup>n</sup> guesses to crack by brute
        force. Each bit of entropy doubles the search space.
      </p>

      <h2>Password Entropy by Character Set</h2>
      <table>
        <thead>
          <tr>
            <th>Character Set</th>
            <th>Size</th>
            <th>Bits per character</th>
            <th>12-char entropy</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Lowercase only (a–z)</td>
            <td>26</td>
            <td>4.7 bits</td>
            <td>56 bits</td>
          </tr>
          <tr>
            <td>+ Uppercase (A–Z)</td>
            <td>52</td>
            <td>5.7 bits</td>
            <td>68 bits</td>
          </tr>
          <tr>
            <td>+ Digits (0–9)</td>
            <td>62</td>
            <td>5.95 bits</td>
            <td>71 bits</td>
          </tr>
          <tr>
            <td>+ Symbols (!@#$…)</td>
            <td>94</td>
            <td>6.55 bits</td>
            <td>78 bits</td>
          </tr>
        </tbody>
      </table>
      <p>
        A 12-character password using all character types has ~78 bits of entropy. At 10 billion
        guesses per second (a realistic GPU cracking speed), exhausting this space would take longer
        than the age of the universe. A 6-character lowercase password? About 3 minutes.
      </p>

      <h2>Length Beats Complexity</h2>
      <p>
        Adding one more character to a password increases its entropy by ~6.5 bits — doubling the
        effective search space 6.5 times. Forcing users to add a symbol instead of making the
        password longer often results in <em>less</em> secure passwords because users choose
        predictable substitutions: <code>p@ssw0rd</code> instead of a random longer string.
      </p>
      <p>
        The current NIST recommendation (SP 800-63B) prioritizes length over complexity rules, and
        recommends checking passwords against known breach lists rather than enforcing arbitrary
        symbol requirements.
      </p>

      <h2>How Password Crackers Work</h2>
      <p>Attackers do not start with random brute force. They use ordered strategies:</p>
      <ol>
        <li>
          <strong>Dictionary attacks</strong> — try words from dictionaries and known leaked
          password lists (rockyou.txt has 14 million real passwords).
        </li>
        <li>
          <strong>Rule-based attacks</strong> — apply transformations to dictionary words: capitalize
          first letter, append a digit, substitute <code>e→3</code>, <code>a→@</code>.
        </li>
        <li>
          <strong>Hybrid attacks</strong> — combine words: <code>correct-horse-battery-staple</code>{' '}
          is memorable but a hybrid cracker will try word combinations.
        </li>
        <li>
          <strong>Brute force</strong> — try every possible combination. Only practical for short
          passwords.
        </li>
      </ol>
      <p>
        The most secure passwords are <strong>random</strong> — generated by a machine, not chosen
        by a human. Human-chosen passwords follow predictable patterns even when the user thinks
        they're being creative.
      </p>

      <h2>Cryptographically Secure vs Math.random()</h2>
      <p>
        Not all random number generators are equal. JavaScript's <code>Math.random()</code> is a
        pseudorandom number generator (PRNG) — fast, but predictable given the seed. It is{' '}
        <strong>not suitable for generating passwords or security tokens</strong>.
      </p>
      <p>
        The <strong>Web Crypto API</strong> (<code>crypto.getRandomValues()</code>) uses the
        operating system's cryptographically secure random source, which draws from hardware entropy
        (CPU timing jitter, mouse movement, etc.). This is what secure password generators use.
      </p>
      <pre><code>{`// ❌ Insecure — don't use for passwords
const random = Math.random()

// ✅ Cryptographically secure
const array = new Uint32Array(1)
crypto.getRandomValues(array)
const random = array[0]`}</code></pre>

      <h2>Recommended Password Lengths</h2>
      <table>
        <thead>
          <tr>
            <th>Use Case</th>
            <th>Minimum Length</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>General accounts</td>
            <td>16 characters</td>
            <td>Use a password manager</td>
          </tr>
          <tr>
            <td>Banking / email</td>
            <td>20+ characters</td>
            <td>High-value targets</td>
          </tr>
          <tr>
            <td>Master password</td>
            <td>24+ characters</td>
            <td>Memorize this one</td>
          </tr>
          <tr>
            <td>API keys / secrets</td>
            <td>32+ characters</td>
            <td>Full random, store in vault</td>
          </tr>
          <tr>
            <td>Encryption keys</td>
            <td>128+ bits</td>
            <td>Use a KDF, not raw password</td>
          </tr>
        </tbody>
      </table>

      <h2>Password Managers</h2>
      <p>
        The only practical way to use long, unique, random passwords for every site is a password
        manager. It generates and stores credentials so you only remember one strong master
        password.
      </p>
      <p>
        Reusing passwords is the biggest real-world risk. When a site is breached and passwords are
        leaked, attackers immediately try those credentials on Gmail, banking, and other services —
        a technique called <strong>credential stuffing</strong>. A unique password per site limits
        the blast radius to a single account.
      </p>

      <h2>Multi-Factor Authentication</h2>
      <p>
        Even a perfect password is not enough if it is phished or leaked. Enable multi-factor
        authentication (MFA) on every account that supports it. Authenticator apps (TOTP like
        Google Authenticator) are more secure than SMS. Hardware keys (YubiKey) are the most secure
        option for high-value accounts.
      </p>

      <h2>What to Avoid</h2>
      <ul>
        <li>Dictionary words, even with substitutions (<code>p@ssw0rd</code>)</li>
        <li>Personal information: birthdays, names, pets</li>
        <li>Keyboard walks: <code>qwerty</code>, <code>123456</code>, <code>asdfgh</code></li>
        <li>Reusing passwords across sites</li>
        <li>Storing passwords in plain text, spreadsheets, or notes apps</li>
        <li>Sharing passwords over email or chat</li>
      </ul>
    </article>
  )
}
